// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/getAccount": {
            "post": {
                "description": "根据提供的邮箱获取对应用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "获取账户信息",
                "parameters": [
                    {
                        "description": "获取账户请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/account.GetAccountVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/account/loginAccount": {
            "post": {
                "description": "用户登录并获取访问令牌，支持图形验证码校验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "图形验证码",
                        "name": "ImgVerificationCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回访问令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/account.LoginVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误，验证码校验失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "401": {
                        "description": "登录失败，凭证无效",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/account/logoutAccount": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "退出当前用户登录状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/account/registerAccount": {
            "post": {
                "description": "注册新用户账号，支持图形验证码和邮箱验证码校验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "图形验证码",
                        "name": "ImgVerificationCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮箱验证码",
                        "name": "EmailVerificationCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RegisterRequest"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误，验证码校验失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/account/resetPassword": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "重置用户账户密码，支持邮箱验证码校验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "重置密码信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPwdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "密码重置成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误，验证码校验失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "401": {
                        "description": "未授权，用户未登录",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/category/createOneCategory": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的类目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类目"
                ],
                "summary": "创建类目",
                "parameters": [
                    {
                        "description": "创建类目请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOneCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/category.CategoriesVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/category/deleteOneCategory": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据类目 ID 删除类目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类目"
                ],
                "summary": "删除类目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "类目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/category.CategoriesVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "类目不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/category/getCategoryChildrenTree": {
            "post": {
                "description": "根据类目 ID 获取子类目树",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类目"
                ],
                "summary": "获取子类目树",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "类目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/category.CategoriesVO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "类目不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/category/getCategoryTree": {
            "get": {
                "description": "获取类目树",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类目"
                ],
                "summary": "获取类目树",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/category.CategoriesVO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/category/getOneCategory": {
            "get": {
                "description": "根据类目 ID 获取单个类目的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类目"
                ],
                "summary": "获取单个类目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "类目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/category.CategoriesVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "类目不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/category/updateOneCategory": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新已存在的类目信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类目"
                ],
                "summary": "更新类目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "类目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新类目请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateOneCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/category.CategoriesVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "类目不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/comment/createOneComment": {
            "post": {
                "description": "创建一条新的评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "创建评论",
                "parameters": [
                    {
                        "description": "创建评论请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/comment.CommentsVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/comment/deleteOneComment": {
            "post": {
                "description": "通过评论 ID 进行软删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "软删除评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "软删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/comment.CommentsVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "评论不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/comment/getOneComment": {
            "get": {
                "description": "根据文章 ID 获取评论图结构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "获取评论图",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文章ID",
                        "name": "post_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/comment.CommentsVO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/oss/deleteFile": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从 MinIO 对象存储删除文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "对象存储"
                ],
                "summary": "删除文件",
                "parameters": [
                    {
                        "description": "删除文件请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteOneFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/oss/downloadFile": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从 MinIO 对象存储下载文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "对象存储"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "description": "下载文件请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DownloadOneFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/oss/listObjects": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "列出 MinIO 对象存储中的文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "对象存储"
                ],
                "summary": "列出对象",
                "parameters": [
                    {
                        "description": "列出对象请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ListAllObjectsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/oss/uploadFile": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传文件到 MinIO 对象存储",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "对象存储"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "要上传的文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "存储桶名称",
                        "name": "bucket_name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/post/createOnePost": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的文章，支持 Markdown 格式内容，系统会自动转换为 HTML",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章"
                ],
                "summary": "创建文章",
                "parameters": [
                    {
                        "description": "创建文章请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOnePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/post.PostsVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/post/deleteOnePost": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据文章 ID 删除指定文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章"
                ],
                "summary": "删除文章",
                "parameters": [
                    {
                        "description": "删除文章请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteOnePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "文章不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/post/getAllPosts": {
            "get": {
                "description": "获取所有的文章列表，按创建时间倒序排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章"
                ],
                "summary": "获取文章列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/post.PostsVO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/post/getOnePost": {
            "get": {
                "description": "根据文章 ID 获取文章的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章"
                ],
                "summary": "获取文章详情",
                "parameters": [
                    {
                        "description": "获取文章请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetOnePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/post.PostsVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "文章不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/post/updateOnePost": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新已存在的文章内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章"
                ],
                "summary": "更新文章",
                "parameters": [
                    {
                        "description": "更新文章请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateOnePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/post.PostsVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "404": {
                        "description": "文章不存在",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/test/testErrRes": {
            "get": {
                "description": "用于测试错误响应",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/test/testErrorMiddleware": {
            "get": {
                "description": "用于测试错误中间件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/testHello": {
            "get": {
                "description": "测试接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "200": {
                        "description": "Hello, Jank 🎉!\\n",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/testLogger": {
            "get": {
                "description": "用于测试日志功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "200": {
                        "description": "测试日志成功!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/testLongReq": {
            "get": {
                "description": "模拟一个耗时请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "200": {
                        "description": "模拟耗时请求处理完成!\\n",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/testPing": {
            "get": {
                "description": "测试接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "200": {
                        "description": "Pong successfully!\\n",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/testRedis": {
            "get": {
                "description": "用于测试 Redis 功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "200": {
                        "description": "测试缓存功能完成!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/testSuccessRes": {
            "get": {
                "description": "用于测试成功响应",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "responses": {
                    "200": {
                        "description": "测试成功响应成功!",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/verification/sendEmailVerificationCode": {
            "get": {
                "description": "向指定邮箱发送验证码，验证码有效期为3分钟",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱地址，用于发送验证码",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "邮箱验证码发送成功, 请注意查收邮件",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，邮箱地址为空",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    },
                    "500": {
                        "description": "服务器错误，邮箱验证码发送失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Result"
                        }
                    }
                }
            }
        },
        "/verification/sendImgVerificationCode": {
            "get": {
                "description": "生成单个图形验证码并将其返回为Base64编码字符串，用户可以用该验证码进行校验。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "生成图形验证码并返回Base64编码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱地址，用于生成验证码",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回验证码的Base64编码",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误，邮箱地址为空",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误，生成验证码失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.GetAccountVO": {
            "description": "请求获取账户信息时所需参数",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "account.LoginVO": {
            "description": "登录成功后返回的访问令牌和刷新令牌",
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "category.CategoriesVO": {
            "description": "获取类目响应",
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/category.CategoriesVO"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "comment.CommentsVO": {
            "description": "获取单个评论的响应",
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "replies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comment.CommentsVO"
                    }
                },
                "reply_to_comment_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateCommentRequest": {
            "type": "object",
            "required": [
                "content",
                "post_id",
                "user_id"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 1
                },
                "post_id": {
                    "type": "integer"
                },
                "reply_to_comment_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateOneCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateOnePostRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "content_markdown": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 225,
                    "minLength": 1
                },
                "visibility": {
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "dto.DeleteOneFileRequest": {
            "type": "object",
            "required": [
                "bucket_name",
                "object_name"
            ],
            "properties": {
                "bucket_name": {
                    "type": "string",
                    "maxLength": 63,
                    "minLength": 1
                },
                "object_name": {
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 1
                }
            }
        },
        "dto.DeleteOnePostRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.DownloadOneFileRequest": {
            "type": "object",
            "required": [
                "bucket_name",
                "object_name"
            ],
            "properties": {
                "bucket_name": {
                    "type": "string",
                    "maxLength": 63,
                    "minLength": 1
                },
                "object_name": {
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 1
                }
            }
        },
        "dto.GetAccountRequest": {
            "description": "请求获取账户信息时所需参数",
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.GetOnePostRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "default": 0
                }
            }
        },
        "dto.ListAllObjectsRequest": {
            "type": "object",
            "required": [
                "bucket_name"
            ],
            "properties": {
                "bucket_name": {
                    "type": "string",
                    "maxLength": 63,
                    "minLength": 1
                },
                "prefix": {
                    "type": "string",
                    "maxLength": 1024
                }
            }
        },
        "dto.LoginRequest": {
            "description": "用户登录请求所需参数",
            "type": "object",
            "required": [
                "email",
                "img_verification_code",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "img_verification_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.RegisterRequest": {
            "description": "用户注册所需参数",
            "type": "object",
            "required": [
                "email",
                "email_verification_code",
                "img_verification_code",
                "nickname",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "email_verification_code": {
                    "type": "string"
                },
                "img_verification_code": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPwdRequest": {
            "description": "用户重置密码所需参数",
            "type": "object",
            "required": [
                "again_new_password",
                "email",
                "email_verification_code",
                "new_password"
            ],
            "properties": {
                "again_new_password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "email": {
                    "type": "string"
                },
                "email_verification_code": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                }
            }
        },
        "dto.UpdateOneCategoryRequest": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateOnePostRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "content_markdown": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 0
                },
                "visibility": {
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "post.PostsVO": {
            "description": "获取帖子时返回的响应数据",
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "content_html": {
                    "description": "ContentMarkdown string ` + "`" + `json:\"content_markdown\"` + "`" + `",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "visibility": {
                    "type": "boolean"
                }
            }
        },
        "vo.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据"
                },
                "msg": {
                    "description": "错误信息",
                    "type": "string"
                },
                "requestId": {
                    "description": "请求ID"
                },
                "timeStamp": {
                    "description": "响应时间戳"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "输入格式: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9010",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "This is the API documentation for Jank Blog.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
